# Generated by Django 5.1.5 on 2025-01-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial_emotion_tags"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="posts_post_expires_cca490_idx",
        ),
        migrations.RemoveField(
            model_name="post",
            name="expires_at",
        ),
    ]
